### ISSUE TITLE
Return to admin Link

### ISSUE THREAD

**Issue by selwynorren** [ShaunR/template-bootstrap#20]
Hi,

Is it possible to change the return to administrator link to read the admin location from the config file. Currently its hard coded in the header.tpl file to link back to "admin/clientssummary.php?userid={$smarty.session.uid}&amp;return=1"
I have customised my admin location in the config.php file. So I had to change the header.tpl to reflect my admin location, which will be overwritten if there are updates.

P.S Really great work, thank you so much

**Comment by ShaunR** [comment]
I looked into this alittle bit and as far as I can tell there is not a standard/simple way to find this.  I'm sure i could probably hack up the template and pull the var from globals but thats really ugly.  I'm going to look into this more but for the time being you might be better off just making the change by hand on your own repo and committing that change.  I'm going to keep poking around.

**Comment by selwynorren** [comment]
Hi Shaun,
Thanks so much. I did the hand coding thing for now. I will also see if I can find the globals for the admin location, but so far I have not found any that are usable.

I did notice on the other themes that that portion of script is hardcoded from WHMCS's side, so it does not make the job any easier - lol

Again thanks for everything

**Comment by ShaunR** [comment]
Ya, WHMCS decided to hardcode that link into the template.  I submitted requests in the past asking them to stop doing it this way and to add it to the template as it should be.  So far they have ignored this request.  In my template i had to do some dirty css and hide that link (```display: none !important;```).  That link you see now was added by me.  If you really want to use the var you could add the following to your header.tpl... It's ugly though!

```
{php}
global $smarty;
if(isset($GLOBALS['customadminpath']) {
    $smarty->assign('customadminpath',$GLOBALS['customadminpath']);
} else {
    $smarty->assign('customadminpath','admin');
}
{/php}
```

Now you could simply use ```{$customadminpath}``` in your template.

**Comment by selwynorren** [comment]
Thanks Shaun,

I can give that a try
