### ISSUE TITLE
Return to Admin Area don't work when using a different admin slug

### ISSUE THREAD

**Issue by whocarez** [ShaunR/template-bootstrap#23]
When we login as a client from Admin, then back to Admin area link when work.

**Comment by ShaunR** [comment]
Can you explain the problem again?  Sounds like your saying the back to admin link is not working.  It works for me though.

**Comment by whocarez** [comment]
Hello,

I wanted to say that like if my admin panel link is
http://example.com/whmcs/admin then Logout and return to admin link is
working fine. but if my admin link is changed like
http://example.com/whmcs/customadmin then your theme takes to default admin.

----------------------------------------------------------
Live Well, Love Much, Laugh Often :-)
    (¨`·.·´¨)
(¨`·.·´¨)¸.·´
`·.¸.·´
With Love
Prateek....

**Comment by ShaunR** [comment]
That is a known issue with this template.  Unfortunately WHMCS doesn't provide a template var with the correct path, they hard code it.  So there is not a simple solution for this really without adding some messy code.  My recommendation would be for you to modify the template to link to the correct location.

Sorry!
